# Generated by Django 3.1 on 2020-09-22 02:20

import badmintonscore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='playername',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='teamnames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('ranking', models.IntegerField()),
                ('photo', models.ImageField(upload_to=badmintonscore.models.teamnames.upload_logo)),
                ('player', models.ManyToManyField(to='badmintonscore.playername')),
            ],
        ),
        migrations.CreateModel(
            name='match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.CharField(default='', max_length=10, unique=True)),
                ('match_category', models.CharField(max_length=100)),
                ('score_A', models.IntegerField(default=0)),
                ('score_B', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team_nameA', models.ManyToManyField(related_name='team_nameA', to='badmintonscore.teamnames')),
                ('team_nameB', models.ManyToManyField(related_name='team_nameB', to='badmintonscore.teamnames')),
            ],
        ),
    ]
