# Generated by Django 3.1 on 2020-09-24 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badmintonscore', '0002_auto_20200924_0223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='player_name',
        ),
        migrations.AddField(
            model_name='match',
            name='player_name',
            field=models.ManyToManyField(to='badmintonscore.playername'),
        ),
    ]
