# Generated by Django 3.1 on 2020-09-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badmintonscore', '0003_auto_20200924_0233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='player_name',
        ),
        migrations.AddField(
            model_name='match',
            name='player_nameA',
            field=models.ManyToManyField(related_name='playernameA', to='badmintonscore.playername'),
        ),
        migrations.AddField(
            model_name='match',
            name='player_nameB',
            field=models.ManyToManyField(related_name='playernameb', to='badmintonscore.playername'),
        ),
    ]
